# Generated by Django 5.2.4 on 2025-10-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_recruiter_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='message_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
