# Generated by Django 5.2.4 on 2025-10-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_message_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='message_updated_at',
        ),
    ]
