# Generated by Django 5.2.4 on 2025-08-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_required',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
